apiVersion: appdynamics.com/v1alpha1
kind: Clusteragent
metadata:
  name: k8s-cluster-agent
  namespace: appdynamics
spec:
  controllerUrl: "https://saas.appdynamics.com"
  account: "customer1"
  appName: "AutoInstrumentCluster"
  serviceAccountName: appdynamics-cluster-agent
  image: "docker.io/appdynamics/cluster-agent:20.5.0"
  nsToMonitor: [appdynamics,default,dev,stage]



