apiVersion: appdynamics.com/v1alpha1
kind: Clusteragent
metadata:
  name: k8s-cluster-agent
  namespace: appdynamics
spec:
  controllerUrl: "http://saas.appdynamics.com"
  account: "customer1"
  appName: "AutoInstrumentCluster"
  serviceAccountName: appdynamics-cluster-agent
  image: "docker.io/appdynamics/cluster-agent:latest"
  nodeSelector:
    kubernetes.io/os: linux
  nsToMonitor: [appdynamics,default,dev]
  instrumentationMethod: Env
  defaultAnalyticsHost: appd-infraviz.appdynamics.svc.cluster.local
  defaultAnalyticsPort: 9090
  defaultAnalyticsSslEnabled: false
  nsToInstrumentRegex: dev
  defaultAppName: NodeOnlyApp
#  defaultInstrumentMatchString: ^open # set this value if using at least one matchString in rules
  resourcesToInstrument: [Deployment,StatefulSet]
  instrumentationRules:
    - namespaceRegex: dev
      matchString: ^open
      language: nodejs
      appName: NodeAuto
      imageInfo:
        image: "docker.io/appdynamics/nodejs-agent:20.5.0-alpinev10"
        agentMountPath: /opt/appdynamics




