apiVersion: appdynamics.com/v1alpha1
kind: Clusteragent
metadata:
  name: k8s-cluster-agent
  namespace: appdynamics
spec:
  controllerUrl: "http://saas.appdynamics.com"
  account: "customer1"
  appName: "AutoInstrumentCluster"
  serviceAccountName: appdynamics-cluster-agent
  image: "docker.io/appdynamics/cluster-agent:20.5.0"
  nsToMonitor: [appdynamics,default,dev,stage]
  instrumentationMethod: Env
  nsToInstrumentRegex: stage|dev
  defaultAppName: AI-Stage
  resourcesToInstrument: [Deployment,StatefulSet]
  imageInfo:
    java:
      image: "docker.io/appdynamics/java-agent:latest"
      agentMountPath: /opt/appdynamics
  netvizInfo:
    bciEnabled: true
    port: 3892 



