apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "php-ingress"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
  labels:
    app: php-ingress
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: "php-app"
              servicePort: 8080