apiVersion: apps/v1
kind: Deployment
metadata:
  name: caching-services
spec:
  selector:
    matchLabels:
      name: caching-services
  replicas: 1
  template:
    metadata:
      labels:
        name: caching-services
    spec:
      containers:
      - name: caching-services
        image: sashaz/ad-air-go-services:latest
        imagePullPolicy: IfNotPresent
        envFrom:
          - configMapRef:
              name: controller-info
        env:
        - name: APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: appd-key
              name: appd-secret
        - name: TIER_NAME
          value: caching-services
        ports:
        - containerPort: 8080
          protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: caching-services
spec:
  selector:
    name: caching-services
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080