apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-agent-windows
  # namespace: appdynamics
spec:
  selector:
    matchLabels:
      name: analytics-agent-windows
  replicas: 1
  template:
    metadata:
      labels:
        name: analytics-agent-windows
    spec:
      nodeSelector:
        beta.kubernetes.io/os: windows
        kubernetes.io/os: windows
        kubernetes.io/arch: amd64
        #cloud.google.com/gke-nodepool: windows-pool
      tolerations:
      - key: "node.kubernetes.io/os"
        operator: "Equal"
        value: "windows"
        effect: "NoSchedule"
      containers:
      - name: analytics-agent-windows
        envFrom:
        - configMapRef:
            name: analytics-agent-config
        env:
        - name: APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: appd-key
              name: appd-secret
        - name: APPDYNAMICS_AGENT_APPLICATION_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace   
        image: appdynamics/analytics-agent:20.6.0-win
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9090
          protocol: TCP
        # windows analytics agent requires a minimum of 1GB heap space to start.
        resources:
          requests:
             memory: "1Gi"
          limits:
            memory: "1.5Gi"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: analytics-agent-windows
  # namespace: appdynamics
spec:
  selector:
    name: analytics-agent-windows
  ports:
  - name: "9090"
    port: 9090
    targetPort: 9090
    protocol: TCP
status:
  loadBalancer: {}