apiVersion: v1
data:
  APPDYNAMICS_AGENT_ACCOUNT_NAME: customer1
  APPDYNAMICS_AGENT_REUSE_NODE_NAME_PREFIX: Node
  APPDYNAMICS_AGENT_TIER_NAME: Web
  APPDYNAMICS_CONTROLLER_HOST_NAME: saas.appdynamics.com
  APPDYNAMICS_CONTROLLER_PORT: "8090"
  APPDYNAMICS_CONTROLLER_SSL_ENABLED: "false"
  APPDYNAMICS_EVENTS_API_URL: "http://saas.appdynamics.com:9080"
  APPDYNAMICS_GLOBAL_ACCOUNT_NAME: customer1_f1d654a0-266
kind: ConfigMap
metadata:
  name: agent-config-win
