apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticketing-load
spec:
  selector:
    matchLabels:
      name: ticketing-load
  replicas: 1
  template:
    metadata:
      labels:
        name: ticketing-load
    spec:
      containers:
      - name: ticketing-load
        image: sashaz/ad-air-load:latest
        imagePullPolicy: IfNotPresent
        envFrom:
          - configMapRef:
              name: controller-info
        env:
        - name: APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: appd-key
              name: appd-secret
        - name: ENABLE_TICKETING_LOAD
          value: "1"
      restartPolicy: Always