apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  selector:
    matchLabels:
      name: flask-app
  replicas: 2
  template:
    metadata:
      labels:
        name: flask-app
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: appd-account
      containers:
        - name: webapp
          image: sashaz/python-app-appd:v1
          imagePullPolicy: Always
          env:
            - name: APPDYNAMICS_AGENT_VERSION
              value: 20.8.0.2388
            - name: APPD_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
          - name: agent-config
            mountPath: /opt/appdynamics/agent.cfg
            subPath: agent.cfg
          - name: proxy-dir
            mountPath: /tmp/appd/run
          resources:
            limits:
              cpu: 200m
              memory: 900M
            requests:
              cpu: 100m
              memory: 600M
          ports:
          - containerPort: 8080
      restartPolicy: Always
      volumes:
      - name: agent-config
        configMap:
          name: agent-config-python
      - name: proxy-dir
        hostPath:
          path: /tmp/appdynamics
          type: Directory

---
apiVersion: v1
kind: Service
metadata:
  name: flask-app
spec:
  selector:
    name: flask-app
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
