apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-tickets
spec:
  selector:
    matchLabels:
      name: mongo-tickets
  replicas: 1
  template:
    metadata:
      labels:
        name: mongo-tickets
    spec:
      containers:
      - name: mongo-tickets
        image: mongo:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017
          protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-tickets
spec:
  selector:
    name: mongo-tickets
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017