apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-services
spec:
  selector:
    matchLabels:
      name: mock-services
  replicas: 1
  template:
    metadata:
      labels:
        name: mock-services
    spec:
      containers:
      - name: mock-services
        image: sashaz/ad-air-mock-services:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: mock-services
spec:
  selector:
    name: mock-services
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080