apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: loan-services
  name: loan-services
spec:
  selector:
    matchLabels:
      name: loan-services
  template:
    metadata:
      labels:
        name: loan-services
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: agent-config
        env:
        - name: APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: appd-key
              name: appd-secret
        - name: JAVA_OPTS
          value: ' -Djboss.modules.system.pkgs="org.jboss.byteman,com.singularity" 
            -Dappdynamics.agent.accountAccessKey=$(APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY)
            -Dappdynamics.controller.hostName=$(APPDYNAMICS_CONTROLLER_HOST_NAME)
            -Dappdynamics.controller.port=$(APPDYNAMICS_CONTROLLER_PORT) -Dappdynamics.controller.ssl.enabled=$(APPDYNAMICS_CONTROLLER_SSL_ENABLED)
            -Dappdynamics.agent.accountName=$(APPDYNAMICS_AGENT_ACCOUNT_NAME) -Dappdynamics.agent.applicationName=$(APPDYNAMICS_AGENT_APPLICATION_NAME)
            -Dappdynamics.agent.tierName=$(APPDYNAMICS_AGENT_TIER_NAME) -Dappdynamics.agent.reuse.nodeName=true
            -Dappdynamics.agent.reuse.nodeName.prefix=$(APPDYNAMICS_AGENT_REUSE_NODE_NAME_PREFIX) -javaagent:/opt/appdynamics-java/javaagent.jar '
        image: jdbarfield/fin-java:2.0
        imagePullPolicy: IfNotPresent
        name: loan-services
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        volumeMounts:
        - mountPath: /opt/appdynamics-java
          name: appd-agent-repo-java
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - cp
        - -ra
        - /opt/appdynamics/.
        - /opt/temp
        image: docker.io/appdynamics/java-agent:latest
        imagePullPolicy: IfNotPresent
        name: appd-agent-attach
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/temp
          name: appd-agent-repo-java
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccountName: appd-account
      volumes:
      - emptyDir: {}
        name: appd-agent-repo-java

---
apiVersion: v1
kind: Service
metadata:
  name: loan-services
spec:
  selector:
    name: loan-services
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080