apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  selector:
    matchLabels:
      name: kafka
  replicas: 1
  template:
    metadata:
      labels:
        name: kafka
    spec:
      containers:
      - name: kafka
        image: jdbarfield/ad-fin2-kafka:2019-03-01-1551446376
        imagePullPolicy: IfNotPresent
        env:
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: kafka
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper:2181"
        - name: KAFKA_CREATE_TOPICS
          value: flight-services,customer-services
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_PORT
          value: "9092"
        ports:
        - containerPort: 9092
          protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  selector:
    name: kafka
  ports:
  - name: "9092"
    port: 9092
    targetPort: 9092