apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
spec:
  selector:
    matchLabels:
      name: zookeeper
  replicas: 1
  template:
    metadata:
      labels:
        name: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: jdbarfield/zookeeper:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 2181
          protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  selector:
    name: zookeeper
  ports:
  - name: "2181"
    port: 2181
    targetPort: 2181