apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: flask-app
    spec:
      serviceAccountName: appd-account
      containers:
        - name: proxy
          image: sashaz/python-proxy:v1
          imagePullPolicy: Always
          env:
            - name: APPD_PROXY_CONTROL_PATH
              value: /tmp/appd/run
          volumeMounts:
          - name: shared-data
            mountPath: /tmp/appd/run
          resources:
            limits:
              cpu: 500m
              memory: 900M
            requests:
              cpu: 400m
              memory: 600M
        - name: webapp
          image: sashaz/python-app-appd:v1
          imagePullPolicy: Always
          env:
            - name: APPD_PROXY_CONTROL_PATH
              value: /tmp/appd/run
          volumeMounts:
          - name: shared-data
            mountPath: /tmp/appd/run
          - name: agent-config
            mountPath: /opt/appdynamics/agent.cfg
            subPath: agent.cfg
          resources:
            limits:
              cpu: 200m
              memory: 900M
            requests:
              cpu: 100m
              memory: 600M
          ports:
          - containerPort: 8080
      restartPolicy: Always
      volumes:
      - name: shared-data
        emptyDir: {}
      - name: agent-config
        configMap:
          name: agent-config-python

---
apiVersion: v1
kind: Service
metadata:
  name: flask-app
spec:
  selector:
    name: flask-app
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
